language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "1.0"
  - "1.8"
  - "2.0"
  - "2.1"
  - "4.2.1"
  - "4.3.1"
  - "5.0.0"
  - "5.7.0"
  - "6.2.2"
  - "6.3.0"
  - "6.4.0"
  - "6.5.0"
sudo: false
cache:
  directories:
    - node_modules
before_install:
  # Setup Node.js version-specific dependencies
  - "npm rm --save-dev istanbul"
  # Update Node.js modules
  - "test ! -d node_modules || npm prune"
  - "test ! -d node_modules || npm rebuild"
  - "npm install mocha"
  - "npm install istanbul"
script:
  # Run test script, depending on istanbul install
  - "test ! -z $(npm -ps ls istanbul) || npm test"
  - "test   -z $(npm -ps ls istanbul) || npm run-script test-ci"
after_script:
  - "test -e ./coverage/lcov.info && npm install coveralls && cat ./coverage/lcov.info | coveralls"
