language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "1.0"
  - "1.8"
  - "2.0"
  - "2.1"
  - "4.2.1"
  - "5.0.0"
sudo: false
before_script:
  - "npm install mocha"
  - "npm install istanbul"
script: "npm run-script test-ci"
after_script: "npm install coveralls && cat ./coverage/lcov.info | coveralls"
