language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "1.0"
  - "1.8"
  - "2.0"
  - "2.1"
  - "4.2"
  - "4.3"
  - "5.0"
  - "5.7"
  - "6.2"
  - "6.3"
  - "6.4"
  - "6.5"
  - "6.6"
  - "7.0"
  - "7.1"
  - "7.2"
  - "7.3"
  - "7.4"
  - "7.5"
sudo: false
before_script:
  - "npm install mocha"
  - "npm install istanbul"
script: "npm run-script test-ci"
after_script: "npm install coveralls && cat ./coverage/lcov.info | coveralls"
