environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "9"
    - nodejs_version: "10"
    - nodejs_version: "11"
platform:
  - x86
  - x64
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm install nyc
  - npm install mocha
  - npm install codecov
build: off
test_script:
  - node --version
  - npm --version
  - npm run test-cov
  - npm run coverage
version: "{build}"
