environment:
  matrix:
    - nodejs_version: "0.10"
    - nodejs_version: "0.12"
    - nodejs_version: "1.8"
    - nodejs_version: "2.5"
    - nodejs_version: "3.3"
    - nodejs_version: "4.2"
    - nodejs_version: "5.3"
    - nodejs_version: "6.2"
    - nodejs_version: "6.3"
    - nodejs_version: "6.5"
install:
  - ps: Install-Product node $env:nodejs_version
build: off
# run scripts before tests
before_test:
  - npm install
  - npm install mocha
  - npm install istanbul
# run tests
test_script:
  - node --version
  - npm --version
  - npm run test-ci
# run scripts after tests
after_test: "npm install coveralls && cat ./coverage/lcov.info | coveralls"
